### ISSUE TITLE
Create Prettier config

### ISSUE THREAD

**Issue by Eldemarkki** [Testaustime/testaustime-frontend#17]

**Comment by kymppi** [comment]
I can handle this today, i think you have to make a config to tell prettiet to use eslint rules.

**Comment by Chicken** [comment]
```
{
    "printWidth": 
    "tabWidth": "semi": true,
        "singleQuote": false,
        "quoteProps": "as-needed",
        "trailingComma": "es5",
        "bracketSpacing": true,
        "arrowParens": "always",
        "endOfLine": "lf"
    }
```

**Comment by Eldemarkki** [comment]
@Chicken if that works, I'm impressed by your speed. However, `"tabWidth": 4` is sus 🤨

**Comment by kymppi** [comment]
Use [this](https://prettier.io/docs/en/integrating-with-linters.html) as a guide for implementing
