### ISSUE TITLE
Use Cookies rather than Local Storage

### ISSUE THREAD

**Issue by feyli** [Testaustime/testaustime-frontend#212]
Local Storage is far from being secure. While you don't get any resources from an external source, the client could be exposed to malicious browser extensions. Generally, it is a better practice to use cookies rather than Local Storage.
This issue might as well fit in the backend repository.

**Comment by KasperiP** [comment]
+1 for this.

**Comment by Eldemarkki** [comment]
I'm currently in the process of migrating to Next.js, and it will make using cookies easier. I will include cookies in the same pull request that also contains Next.js. I can't really give a time estimate, but it will probably be during next week or the week after that.
