### ISSUE TITLE
Time per day chart should work correctly when all entries have duration=0

### ISSUE THREAD

**Issue by Eldemarkki** [Testaustime/testaustime-frontend#35]
This is what happens in those situations:
![image](https://user-images.githubusercontent.com/38920928/162807505-34d87c92-d29c-4f0b-827d-59f8a5e7e33a.png)

**Comment by Esinko** [comment]
![image](https://user-images.githubusercontent.com/34211401/166118945-a5320e34-0a32-4a61-8960-6ec97b84f9ae.png)
Is this the desired behaviour?
If so, I can make a PR for my fix.

**Comment by Eldemarkki** [comment]
@Esinko no, ”None” should be at the bottom. The top value should probably be 1 hour with 10 minute increments
