### ISSUE TITLE
Add support for secured access tokens

### ISSUE THREAD

**Issue by lajp** [Testaustime/testaustime-frontend#357]
[Added and documented by this pr](https://github.com/Testaustime/testaustime-backend/pull/85)

Some details available [here](https://github.com/Testaustime/testaustime-backend/blob/main/docs/APISPEC.md#securedaccess)

Idk if there is a list of endpoints that require a sec_token but one should be able to find all of them just by searching [the APISPEC](https://github.com/Testaustime/testaustime-backend/blob/main/docs/APISPEC.md) for `sec_token`

**Comment by Eldemarkki** [comment]
Done in #412
