### ISSUE TITLE
TypeError when adding a friend

### ISSUE THREAD

**Issue by KasperiP** [Testaustime/testaustime-frontend#48]
This happens when adding a friend (Allow more data as a friend: ```ttfc_Y4De0Kek2AitCz9CfzMs7k2K```). The whole friends page becomes unreachable. 

![image](https://user-images.githubusercontent.com/26027985/167601309-e6bc2db4-ea47-4087-8915-f22b54b94ce1.png)
![image](https://user-images.githubusercontent.com/26027985/167601640-0c919d75-17a5-4b7c-a2c8-cb9bd94dbb92.png)

**Comment by KasperiP** [comment]
This gets fixed after page refresh and it shows bot's statistics correctly after that.

![image](https://user-images.githubusercontent.com/26027985/167602208-be479a09-6ac1-4c37-8fff-57a581a09a1c.png)

**Comment by Eldemarkki** [comment]
This is a problem with the backend, I have made the commit there (https://github.com/Testaustime/testaustime-backend/commit/7f913745713972b2b836b4769a877764a9dab8ff), but apparently it is not in production yet.

**Comment by Eldemarkki** [comment]
Fixed
