### ISSUE TITLE
The "All time" view is slowly becoming messy

### ISSUE THREAD

**Issue by Eldemarkki** [Testaustime/testaustime-frontend#61]
The lines are too dense, they should show data with an appropriate range, for example, time coded in 2-week buckets
![image](https://user-images.githubusercontent.com/38920928/178054487-97882b07-5200-4411-ab47-8b68a06ec7cf.png)

**Comment by KasperiP** [comment]
I would recommend showing all time statistics in 1 month buckets for the clarity (easiest to display). Later also year bucket could be relevant. 

For the reference this is how Stripe displays their "all-time" statistics on their dashboard, which is pretty clean looking IMO:
![image](https://user-images.githubusercontent.com/26027985/210859498-5210ac97-3317-4340-8016-6f4746e1b7f6.png)
![image](https://user-images.githubusercontent.com/26027985/210859585-c94656a3-ce0e-41b9-855c-efea3ad74504.png)
